version: 0.0.104-alpha-build{build}
image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
    - dev
    - /^release\/.$/
    - /^(.*\/)?ci-.*$/
nuget:
  account_feed: true
  project_feed: true
before_build:
  - cmd: nuget restore -Verbosity quiet
build:
  verbosity: minimal
build_script:
  - ps: ./run.ps1
clone_depth: 1
test: 'off'
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/wangkanai/api/v3/package
  api_key:
    secure: YY8jIrOCrsuVBg/iqwS2jVwZ462EWKFMZ+95fBEDqM1DiH0H2w7OMgUx3rQ3XTzl
  artifact: /.*\.nupkg/
  on:
    branch: dev
